### ISSUE TITLE
how to integrate the tag_editor like drop down?

### ISSUE THREAD

**Issue by maheshlalu** [panuavakul/material_tag_editor#2]
How to choose the values form list

**Comment by panuavakul** [comment]
Hi, by drop down, I'm assuming you mean something like
https://material-ui.com/components/autocomplete/

Currently, it is not supported out of the box one way you could do it is with a Stack or an Overlay the same way you would do it with normal TextField.
I think I can probably implement it by next week or two when I have free time.

**Comment by panuavakul** [comment]
Looking at how different apps implement their drop down differently, maybe this implementation should not be part of this library. I will close this for now. Please feel free to create another issue if you want further discussion on this.
