### ISSUE TITLE
Please add controller parameter

### ISSUE THREAD

**Issue by HeebeLee** [panuavakul/material_tag_editor#20]
I need to be able to control this variable freely.
For example, when the user enters content, but does not press the space or comma, I can help it complete the filling.

This parameter needs to be exposed.

**Comment by HeebeLee** [comment]
like this
```
class _TagsEditorState extends State<TagEditor> {
  TextEditingController _textFieldController;
....

  @override
  void initState() {
    super.initState();
    _textFieldController = widget.controller ?? TextEditingController();
...
  }
```

**Comment by panuavakul** [comment]
Hi, thanks for the input and sorry for the late response. I was really busy the past two weeks. I will take a look at this in the weekend.
