### ISSUE TITLE
Suggestion new features - Not null tags

### ISSUE THREAD

**Issue by edukmattos** [panuavakul/material_tag_editor#22]
Congratulations for the package !
I have a suggestion:
Dontt allow the inclusion of the tag if two spaces are entered in sequence at the beginning of the filling

**Comment by panuavakul** [comment]
Hi @edukmattos , thank you for your suggestion.
It's possible to prevent this. However, I'm not too sure about what to do if the delimiter are enter twice.
Maybe we can just not allow delimiters to be input? 🤔 
If you have and desire behaviour please let me know.
