### ISSUE TITLE
The pub version requires Widget type Chip

### ISSUE THREAD

**Issue by lukepighetti** [panuavakul/material_tag_editor#3]
Can you please upload the latest version where tagBuilder allows type `Widget`? The version on Pub requires the type `Chip`.

<img width="579" alt="Screen Shot 2020-07-23 at 8 49 33 PM" src="https://user-images.githubusercontent.com/666539/88351928-0421d980-cd26-11ea-8f19-1784c5d68bab.png">

**Comment by panuavakul** [comment]
@lukepighetti  Hi I fixed this in https://github.com/panuavakul/material_tag_editor/pull/6 and just released `0.0.2`.
Could you try out `0.0.2` and see if that fix this problem for you?
