### ISSUE TITLE
Textfield chips does not support multilines.

### ISSUE THREAD

**Issue by Govindbetterlives** [panuavakul/material_tag_editor#34]
Hi, i need this type of design inside the textfiled. anyone help for this.
thanks.

![tag](https://user-images.githubusercontent.com/81243940/139851127-26b4711f-e991-491f-afea-c07d206dadaa.png)

**Comment by panuavakul** [comment]
Hi @Govindbetterlives , sorry for my late reply. I have not look at this recently. However, it should support multiple lines of text as shown in the Readme.

<img width="625" alt="Screen Shot 2022-02-01 at 14 11 11" src="https://user-images.githubusercontent.com/18391546/151915964-b3d1a610-df60-4d1e-ac58-74eb851079e4.png">

If you can't get it to work, I will be happy to look at some of the code you have written.
Thanks

**Comment by clay4649** [comment]
I will close this. Feel free to make another issue if you need any more help.
