### ISSUE TITLE
Allow more control over the text box

### ISSUE THREAD

**Issue by lukepighetti** [panuavakul/material_tag_editor#4]
Allow things like

multiline, so `'\n'` can be a delimiter
changing the `done` to something of our choosing, ie `next`
enable `autofocus` or disable `autocorrect`
filtering function so we can do things like `.trim()`

**Comment by panuavakul** [comment]
I also agree that we need to pass these probs to the text field. I think this is easy enough that I can probably do it in the weekend.

**Comment by panuavakul** [comment]
This should be resolved in the new release (0.0.3) 
https://github.com/panuavakul/material_tag_editor/releases/tag/0.0.3
Thanks again for the suggestions.
