### ISSUE TITLE
Allow us to set submit to complete the tag instead of dismissing the keyboard

### ISSUE THREAD

**Issue by lukepighetti** [panuavakul/material_tag_editor#5]

**Comment by panuavakul** [comment]
Hi @lukepighetti , thanks for the feedback. Can you elaborate more on the subject?
The `TagEditor` does not really maintain any state (eg. your tag information) so it relies you to keep the state somewhere else (in the `StatefulWidget` or other state management like Redux). So I think you can incorporate `TagEditor` into your own form with your desire submit behaviour.

**Comment by panuavakul** [comment]
After thinking about it I think I understand what you meant. So like when you tab `Done` button in iOS you want some custom action? Is this accurate? I think it isn't hard to implement and can probably do it this weekend.

**Comment by lukepighetti** [comment]
Hey! We're no longer using this package so feel free to close this. Thanks for the support!

**Comment by panuavakul** [comment]
https://github.com/panuavakul/material_tag_editor/pull/10
